services:
  boxy-run:
    image: ${DOCKER_USERNAME:-lcaohoanq}/boxy-run:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: boxy-run-server
    restart: unless-stopped
    ports:
      - '${PORT:-3000}:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MAX_PLAYERS=${MAX_PLAYERS:-50}
      - ENABLE_ROOM_BROWSER=${ENABLE_ROOM_BROWSER:-true}
      - ROOM_CLEANUP_INTERVAL=${ROOM_CLEANUP_INTERVAL:-300000}
    volumes:
      # Optional: Mount logs directory
      - ./logs:/app/logs
    networks:
      - boxy-run-network
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "require('http').get('http://localhost:3000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - 'com.boxy-run.description=History Sufers Multiplayer Game Server'
      - 'com.boxy-run.version=${VERSION:-latest}'
    # Resource limits (adjust based on your server)
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

networks:
  boxy-run-network:
    driver: bridge

volumes:
  logs:
    driver: local
